### ISSUE TITLE
cannot click the node-red Deploy button

### ISSUE THREAD

**Issue by JonMurphy** [hjespers/node-red-contrib-nest#7]
I did the install of 0.1.9 and things did not work as well as expected.  I cannot change any node or change any flow since the Deploy no longer works.  At the moment I am note sure if this is a Node-RED issue or a node-red-contrib-nest issue.

Environment:
- Raspberry Pi 2B
- Jessie
- Node-RED version: v0.14.6
- Node.js  version: v4.4.7
- Linux 4.4.13-v7+ arm LE

And here is the commands I ran (below).  All of my `node-red-contribute-*` installs are done without "-g" (global)

```
pi@emonpi:~/.node-red $ rpi-rw
Filesystem is unlocked - Write access
type ' rpi-ro ' to lock
pi@emonpi:~/.node-red $ sudo npm install node-red-contrib-nest
node-red-contrib-nest@0.1.9 node_modules/node-red-contrib-nest
└── request@2.74.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, aws4@1.4.1, extend@3.0.0, tough-cookie@2.3.1, node-uuid@1.4.7, qs@6.2.1, combined-stream@1.0.5, mime-types@2.1.11, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6, form-data@1.0.1)
```

I've tried a nodered restart and I tried a RasPi reboot.  There doesn't appear to be anything odd in the syslog (I think this is where node-red stores its messages).

I am curious if any of the dependencies above are new or different. 

Any hints would be greatly appreciated!  Thank you!   Jon

**Comment by hjespers** [comment]
If you "sudo npm uninstall node-red-contrib-nest" does the problem go away?

**Comment by JonMurphy** [comment]
No.  
Does `sudo npm uninstall node-red-contrib-nest` remove all of its dependencies also?

**Comment by hjespers** [comment]
Yes npm uninstall "uninstalls a package, completely removing everything npm installed on its behalf."

https://docs.npmjs.com/cli/uninstall

You can double check that you no longer have a sub-directory called node-red-contrib-nest in your ~/.node-red/node_modules directory

**Comment by JonMurphy** [comment]
Thanks!  I'll keep digging.  Jon

**Comment by JonMurphy** [comment]
Hans - looks like the issue with Deploy may be a node-red bug (still waiting on a determination if it was a pilot error or a bug).  Nick looked over my flows and found the fix.
`https://groups.google.com/forum/#!topic/node-red/-PYF08I_nRQ/discussion`
Thank you for your help!
